# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 557151975878f7487e598857f5c4c6a1d66283bd625e24c958e6da8a28fa097ac0f1cc624907297a4f74edbbfde87a8208216058dc5298b30e3f31aa68facacc

test:
  secret_key_base: 959e72673b908a4152ef5431bbd3a757edc571c1197b193e3425bf2846f202236088b27ad65e44e2ac067031aef252cc17d93b77e7bff56b0acb915a33939a36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
